spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: client
              # the client secret is "secret" (without quotes)
              client-secret: "{bcrypt}$2a$10$XjVMlFHKh8yrO349hLMBlOZdGv/KU.WdTFGuBIBS9UZ6cC0feKsY2"
              client-authentication-methods: client_secret_basic
              authorization-grant-types: client_credentials,authorization_code,refresh_token
              scopes: user.read,user.write,openid
              redirect-uris: http://127.0.0.1:8082/login/oauth2/code/spring

            token:
              access-token-time-to-live: 300s

            require-authorization-consent: true



logging:
  level:
    org.springframework.security: TRACE



